
        # QT_SBOM_BUILD_TIME be set to FALSE at install time, so don't override if it's set.
        # This allows reusing the same cmake file for both build and install.
        if(NOT DEFINED QT_SBOM_BUILD_TIME)
            set(QT_SBOM_BUILD_TIME TRUE)
        endif()
        if(NOT QT_SBOM_OUTPUT_PATH)
            set(QT_SBOM_OUTPUT_DIR "/home/noobcod3r-rtx/Documents/GitHub/SmartXm-Cross-Platform-Desktop-Exam-Management-with-Integrated-Judge/Tools/DB_Connector/mysql-kaziRTX/qt_sbom/sbom")
            set(QT_SBOM_OUTPUT_PATH "/home/noobcod3r-rtx/Documents/GitHub/SmartXm-Cross-Platform-Desktop-Exam-Management-with-Integrated-Judge/Tools/DB_Connector/mysql-kaziRTX/qt_sbom/sbom/qsqlitedriverplugins-6.9.2.spdx")
            set(QT_SBOM_OUTPUT_PATH_WITHOUT_EXT "/home/noobcod3r-rtx/Documents/GitHub/SmartXm-Cross-Platform-Desktop-Exam-Management-with-Integrated-Judge/Tools/DB_Connector/mysql-kaziRTX/qt_sbom/sbom/qsqlitedriverplugins-6.9.2")
            file(MAKE_DIRECTORY "/home/noobcod3r-rtx/Documents/GitHub/SmartXm-Cross-Platform-Desktop-Exam-Management-with-Integrated-Judge/Tools/DB_Connector/mysql-kaziRTX/qt_sbom/sbom")
        endif()
        set(QT_SBOM_VERIFICATION_CODES "")
        include("/home/noobcod3r-rtx/Documents/GitHub/SmartXm-Cross-Platform-Desktop-Exam-Management-with-Integrated-Judge/Tools/DB_Connector/mysql-kaziRTX/qt_sbom/append_document_to_staging.cmake")
include("/home/noobcod3r-rtx/Documents/GitHub/SmartXm-Cross-Platform-Desktop-Exam-Management-with-Integrated-Judge/Tools/DB_Connector/mysql-kaziRTX/qt_sbom/SPDXRef-Package-qsqlitedriverplugins-qt-plugin-QPSQLDriverPlugin.cmake")
include("/home/noobcod3r-rtx/Documents/GitHub/SmartXm-Cross-Platform-Desktop-Exam-Management-with-Integrated-Judge/Tools/DB_Connector/mysql-kaziRTX/qt_sbom/SPDXRef-PackagedFile-qt-plugin-QPSQLDriverPlugin.cmake")
include("/home/noobcod3r-rtx/Documents/GitHub/SmartXm-Cross-Platform-Desktop-Exam-Management-with-Integrated-Judge/Tools/DB_Connector/mysql-kaziRTX/qt_sbom/SPDXRef-Package-qsqlitedriverplugins-qt-plugin-QMYSQLDriverPlugin.cmake")
include("/home/noobcod3r-rtx/Documents/GitHub/SmartXm-Cross-Platform-Desktop-Exam-Management-with-Integrated-Judge/Tools/DB_Connector/mysql-kaziRTX/qt_sbom/SPDXRef-PackagedFile-qt-plugin-QMYSQLDriverPlugin.cmake")
include("/home/noobcod3r-rtx/Documents/GitHub/SmartXm-Cross-Platform-Desktop-Exam-Management-with-Integrated-Judge/Tools/DB_Connector/mysql-kaziRTX/qt_sbom/SPDXRef-Package-qsqlitedriverplugins-qt-3rdparty-sources-QSQLiteDriverPlugin-Attribution-sqlite.cmake")
include("/home/noobcod3r-rtx/Documents/GitHub/SmartXm-Cross-Platform-Desktop-Exam-Management-with-Integrated-Judge/Tools/DB_Connector/mysql-kaziRTX/qt_sbom/SPDXRef-Package-qsqlitedriverplugins-qt-plugin-QSQLiteDriverPlugin.cmake")
include("/home/noobcod3r-rtx/Documents/GitHub/SmartXm-Cross-Platform-Desktop-Exam-Management-with-Integrated-Judge/Tools/DB_Connector/mysql-kaziRTX/qt_sbom/SPDXRef-PackagedFile-qt-plugin-QSQLiteDriverPlugin.cmake")
include("/home/noobcod3r-rtx/Documents/GitHub/SmartXm-Cross-Platform-Desktop-Exam-Management-with-Integrated-Judge/Tools/DB_Connector/mysql-kaziRTX/qt_sbom/SPDXRef-Package-qsqlitedriverplugins-system-3rdparty-PostgreSQL.cmake")
include("/home/noobcod3r-rtx/Documents/GitHub/SmartXm-Cross-Platform-Desktop-Exam-Management-with-Integrated-Judge/Tools/DB_Connector/mysql-kaziRTX/qt_sbom/SPDXRef-Package-qsqlitedriverplugins-system-3rdparty-MySQL.cmake")
include("/home/noobcod3r-rtx/Documents/GitHub/SmartXm-Cross-Platform-Desktop-Exam-Management-with-Integrated-Judge/Tools/DB_Connector/mysql-kaziRTX/qt_sbom/SPDXRef-LicenseRef-BSD-3-Clause-with-PCRE2-Binary-Like-Packages-Exception-0.cmake")
include("/home/noobcod3r-rtx/Documents/GitHub/SmartXm-Cross-Platform-Desktop-Exam-Management-with-Integrated-Judge/Tools/DB_Connector/mysql-kaziRTX/qt_sbom/SPDXRef-LicenseRef-ICC-License-1.cmake")
include("/home/noobcod3r-rtx/Documents/GitHub/SmartXm-Cross-Platform-Desktop-Exam-Management-with-Integrated-Judge/Tools/DB_Connector/mysql-kaziRTX/qt_sbom/SPDXRef-LicenseRef-Lcs-Telegraphics-2.cmake")
include("/home/noobcod3r-rtx/Documents/GitHub/SmartXm-Cross-Platform-Desktop-Exam-Management-with-Integrated-Judge/Tools/DB_Connector/mysql-kaziRTX/qt_sbom/SPDXRef-LicenseRef-Qt-Commercial-3.cmake")
include("/home/noobcod3r-rtx/Documents/GitHub/SmartXm-Cross-Platform-Desktop-Exam-Management-with-Integrated-Judge/Tools/DB_Connector/mysql-kaziRTX/qt_sbom/SPDXRef-LicenseRef-SHA1-Public-Domain-4.cmake")
include("/home/noobcod3r-rtx/Documents/GitHub/SmartXm-Cross-Platform-Desktop-Exam-Management-with-Integrated-Judge/Tools/DB_Connector/mysql-kaziRTX/qt_sbom/DocumentRef-qtbase.cmake")
        if(QT_SBOM_BUILD_TIME)
            message(STATUS "Finalizing SBOM generation in build dir: ${QT_SBOM_OUTPUT_PATH}")
            configure_file("/home/noobcod3r-rtx/Documents/GitHub/SmartXm-Cross-Platform-Desktop-Exam-Management-with-Integrated-Judge/Tools/DB_Connector/mysql-kaziRTX/qt_sbom/staging-qsqlitedriverplugins.spdx.in" "${QT_SBOM_OUTPUT_PATH}")
            
        endif()
